In [20]:
import silence_tensorflow.auto

In [21]:
import tensorflow as tf
import tensorflow_probability as tfp

In [22]:
_W = tfp.distributions.Bernoulli(probs=0.8, name='weather_original')
D = _W.sample(100)

In [23]:
#W_fit = tf.Variable(0.5)
p_W = tfp.util.TransformedVariable(0.5, bijector=tfp.bijectors.SoftClip(low=0.0, high=1.0), name='theta_weather_fit')


In [24]:
W = tfp.distributions.Bernoulli(probs=p_W, name='weather_fit_distribution')
W.sample(100)

<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1], dtype=int32)>

In [25]:
LL = lambda : - tf.reduce_sum(W.log_prob(D))
LL()
tfp.math.minimize(loss_fn=LL, optimizer=tf.optimizers.Adam(0.1), num_steps=1000)

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([69.31472 , 66.341385, 63.60743 , 61.114304, 58.86123 , 56.84505 ,
       55.060204, 53.4988  , 52.150677, 51.003674, 50.043854, 49.25588 ,
       48.623352, 48.129295, 47.756493, 47.487934, 47.307163, 47.19859 ,
       47.147743, 47.141445, 47.16795 , 47.216984, 47.279785, 47.349022,
       47.41877 , 47.484383, 47.5424  , 47.590405, 47.62688 , 47.65114 ,
       47.66313 , 47.663353, 47.652737, 47.632545, 47.60425 , 47.569485,
       47.529922, 47.487247, 47.443054, 47.39884 , 47.355934, 47.315464,
       47.278347, 47.245274, 47.216713, 47.19289 , 47.173843, 47.159397,
       47.14924 , 47.14291 , 47.13986 , 47.139484, 47.14115 , 47.14425 ,
       47.14819 , 47.152447, 47.156597, 47.16027 , 47.16323 , 47.165302,
       47.16642 , 47.16659 , 47.165882, 47.164413, 47.162327, 47.159805,
       47.157017, 47.154125, 47.151283, 47.148617, 47.14622 , 47.14416 ,
       47.142483, 47.141186, 47.140266, 47.139687, 47.139404, 47.139362,
  

In [31]:
W.value()

AttributeError: 'Bernoulli' object has no attribute 'value'