In [1]:
import numpy as np

X es una matrix extendida de features y input sample de m numero de sample y n numero de features

In [27]:
X = np.array([[1],[3], [-2], [12]])
y = np.array([3, 6, -1, 14])
print(X.shape)
print(np.random.permutation(4))
np.dot(np.array([1,1]), np.array([1,1]))
np.ones((X.shape[0], 1) )
np.hstack((ones, X))
np.hstack((np.array([1]), X[0]))

(4, 1)
[1 3 2 0]
1 [[1.]]


array([1, 1])

In [30]:
def h(Xi, Theta):
    # given a input vector sample of n features add a constant value of dimensionality 1
    # at the beggining of the second dimension of Xi
    # given Theta a vector of n+1 parameters
    # computes the dot product or the linear model prediction given Xi and Theta
    Xi = np.hstack((np.array([1]), Xi))
    return np.dot(Xi, Theta)

In [46]:
def stochastic_gradiend_descend(X, y, alpha=0.01, n_epoch=100):
    m, n = X.shape
    Theta = np.ones(n+1)
    for _ in range(n_epoch):
        for i in np.random.permutation(m):
            l_e = h(X[i], Theta) - y[i] # lineal error 
            grad = l_e * X[i] * 0.5
            Theta -= alpha * grad
    return Theta

In [47]:
print(stochastic_gradiend_descend(X,y))

[1.08493534 1.08493534]


In [48]:
def batch_gradiend_descend(X, y, alpha=0.01, n_iter=1000):
    m, n = X.shape
    Theta = np.ones(n+1)
    ones_matrix = np.ones((m,1))
    X = np.hstack((ones_matrix, X))
    for _ in range(n_iter):
        grad = X.T @ (X@Theta - y) 
        Theta -= (1/m) * alpha * grad
    return Theta

    
batch_gradiend_descend(X, y)

array([1.838587  , 1.04594934])