In [2]:
import numpy as np

In [12]:
x = np.arange(6).reshape(6,1)
X = np.ones_like(x) @ x.T
O = np.ones_like(X)

In [17]:
_x = x.reshape(6,)
O @ X

array([[ 0,  6, 12, 18, 24, 30],
       [ 0,  6, 12, 18, 24, 30],
       [ 0,  6, 12, 18, 24, 30],
       [ 0,  6, 12, 18, 24, 30],
       [ 0,  6, 12, 18, 24, 30],
       [ 0,  6, 12, 18, 24, 30]])

In [20]:
x@x.T

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20],
       [ 0,  5, 10, 15, 20, 25]])

In [23]:
x.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [51]:
M = np.hstack([x,x,x,x,x,x])
acum = np.zeros_like(M)
for i, row_i in enumerate(M.T):
    col_i = M[i]
    print(f"row {i} = {row_i}", f"col {i} = {col_i}", sep='\n'); print()
    acum += row_i @ col_i
M.T
for i, row_i in enumerate(M.T):
    M.T[i] = row_i ** (i+1)
M.T

row 0 = [0 1 2 3 4 5]
col 0 = [0 0 0 0 0 0]

row 1 = [0 1 2 3 4 5]
col 1 = [1 1 1 1 1 1]

row 2 = [0 1 2 3 4 5]
col 2 = [2 2 2 2 2 2]

row 3 = [0 1 2 3 4 5]
col 3 = [3 3 3 3 3 3]

row 4 = [0 1 2 3 4 5]
col 4 = [4 4 4 4 4 4]

row 5 = [0 1 2 3 4 5]
col 5 = [5 5 5 5 5 5]



array([[    0,     1,     2,     3,     4,     5],
       [    0,     1,     4,     9,    16,    25],
       [    0,     1,     8,    27,    64,   125],
       [    0,     1,    16,    81,   256,   625],
       [    0,     1,    32,   243,  1024,  3125],
       [    0,     1,    64,   729,  4096, 15625]])